# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExtractChromeStorage < Formula
  desc ""
  homepage ""
  version "0.0.7"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/shunirr/extract-chrome-storage/releases/download/v0.0.7/extract-chrome-storage_0.0.7_darwin_amd64.tar.gz"
    sha256 "cca2ef612ae1eb6df0ecdcf5263c1366b9bd1ecb403705686c6ec3d743e3f0c9"

    def install
      bin.install "extract-chrome-storage"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/shunirr/extract-chrome-storage/releases/download/v0.0.7/extract-chrome-storage_0.0.7_darwin_arm64.tar.gz"
    sha256 "e2dc1c98dd2c5980e432bf101a0b3559816a734de8532bde203afecdd1ce38b4"

    def install
      bin.install "extract-chrome-storage"
    end
  end
end
