# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExtractChromeStorage < Formula
  desc ""
  homepage ""
  version "0.0.3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/shunirr/extract-chrome-storage/releases/download/v0.0.3/extract-chrome-storage_0.0.3_darwin_amd64.tar.gz"
    sha256 "cbff962a3dd58805a37c5b2dac28fd1503c4dfdc89c07369fda49ab8f17f3348"

    def install
      bin.install "extract-chrome-storage"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/shunirr/extract-chrome-storage/releases/download/v0.0.3/extract-chrome-storage_0.0.3_darwin_arm64.tar.gz"
    sha256 "4a05a447493aa95e775e18c5cf05c6e0f2b8c312b557a1c1bbebf41d6a144724"

    def install
      bin.install "extract-chrome-storage"
    end
  end
end
