# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExtractChromeStorage < Formula
  desc ""
  homepage ""
  version "0.0.9"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/shunirr/extract-chrome-storage/releases/download/v0.0.9/extract-chrome-storage_0.0.9_darwin_amd64.tar.gz"
    sha256 "a1f6eb6458896ef2797dcca0a28056a1225276de541b60ba43b5b69867dd3908"

    def install
      bin.install "extract-chrome-storage"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/shunirr/extract-chrome-storage/releases/download/v0.0.9/extract-chrome-storage_0.0.9_darwin_arm64.tar.gz"
    sha256 "e6347232cf8c66a9b15d7a2c0f27febb4932bd99e2d248c3298cf83a06f3ee8a"

    def install
      bin.install "extract-chrome-storage"
    end
  end
end
